TRANSLATIONS = \
    translation/ar.ts \
    translation/bn.ts \
    translation/de.ts \
    translation/en.ts \
    translation/es.ts \
    translation/fa.ts \
    translation/fr.ts \
    translation/he.ts \
    translation/id.ts \
    translation/it.ts \
    translation/ja.ts \
    translation/ko.ts \
    translation/pl.ts \
    translation/pt_BR.ts \
    translation/pt_PT.ts \
    translation/ru.ts \
    translation/sv.ts \
    translation/tr.ts\
    translation/uk.ts\
    translation/vi.ts \
    translation/zh.ts \
    translation/zh_TW.ts

FORMS += \
    projects/DIE-engine/Controls/dialogbits8.ui \
    projects/DIE-engine/FormatDialogs/dialogdatainspector.ui \
    projects/DIE-engine/FormatDialogs/dialogdump.ui \
    projects/DIE-engine/FormatDialogs/dialogeditstring.ui \
    projects/DIE-engine/FormatDialogs/dialogfindtext.ui \
    projects/DIE-engine/FormatDialogs/dialoggotoaddress.ui \
    projects/DIE-engine/FormatDialogs/dialoghexsignature.ui \
    projects/DIE-engine/FormatDialogs/dialogremove.ui \
    projects/DIE-engine/FormatDialogs/dialogresize.ui \
    projects/DIE-engine/FormatDialogs/dialogsearch.ui \
    projects/DIE-engine/FormatDialogs/dialogsearchprocess.ui \
    projects/DIE-engine/FormatDialogs/dialogshowdata.ui \
    projects/DIE-engine/FormatDialogs/dialogtextinfo.ui \
    projects/DIE-engine/FormatDialogs/xdialogprocess.ui \
    projects/DIE-engine/FormatWidgets/Binary/binarywidget.ui \
    projects/DIE-engine/FormatWidgets/Binary/dialogbinary.ui \
    projects/DIE-engine/FormatWidgets/DEX/dexsectionheaderwidget.ui \
    projects/DIE-engine/FormatWidgets/DEX/dexwidget.ui \
    projects/DIE-engine/FormatWidgets/DEX/dialogdex.ui \
    projects/DIE-engine/FormatWidgets/ELF/dialogelf.ui \
    projects/DIE-engine/FormatWidgets/ELF/elfsectionheaderwidget.ui \
    projects/DIE-engine/FormatWidgets/ELF/elfwidget.ui \
    projects/DIE-engine/FormatWidgets/LE/dialogle.ui \
    projects/DIE-engine/FormatWidgets/LE/lesectionheaderwidget.ui \
    projects/DIE-engine/FormatWidgets/LE/lewidget.ui \
    projects/DIE-engine/FormatWidgets/MACH/dialogmach.ui \
    projects/DIE-engine/FormatWidgets/MACH/machsectionheaderwidget.ui \
    projects/DIE-engine/FormatWidgets/MACH/machwidget.ui \
    projects/DIE-engine/FormatWidgets/MACHOFAT/dialogmachofat.ui \
    projects/DIE-engine/FormatWidgets/MACHOFAT/machofatwidget.ui \
    projects/DIE-engine/FormatWidgets/MSDOS/dialogmsdos.ui \
    projects/DIE-engine/FormatWidgets/MSDOS/msdoswidget.ui \
    projects/DIE-engine/FormatWidgets/NE/dialogne.ui \
    projects/DIE-engine/FormatWidgets/NE/nesectionheaderwidget.ui \
    projects/DIE-engine/FormatWidgets/NE/newidget.ui \
    projects/DIE-engine/FormatWidgets/PDF/dialogpdf.ui \
    projects/DIE-engine/FormatWidgets/PDF/pdfwidget.ui \
    projects/DIE-engine/FormatWidgets/PE/dialogpe.ui \
    projects/DIE-engine/FormatWidgets/PE/pesectionheaderwidget.ui \
    projects/DIE-engine/FormatWidgets/PE/petoolswidget.ui \
    projects/DIE-engine/FormatWidgets/PE/pewidget.ui \
    projects/DIE-engine/FormatWidgets/SearchSignatures/dialogsearchsignatures.ui \
    projects/DIE-engine/FormatWidgets/SearchSignatures/searchsignaturesoptionswidget.ui \
    projects/DIE-engine/FormatWidgets/SearchSignatures/searchsignatureswidget.ui \
    projects/DIE-engine/FormatWidgets/SearchStrings/dialogsearchstrings.ui \
    projects/DIE-engine/FormatWidgets/SearchStrings/searchstringswidget.ui \
    projects/DIE-engine/FormatWidgets/SearchValues/dialogsearchvalues.ui \
    projects/DIE-engine/FormatWidgets/SearchValues/searchvalueswidget.ui \
    projects/DIE-engine/FormatWidgets/dialogmodelinfo.ui \
    projects/DIE-engine/FormatWidgets/dialogsectionheader.ui \
    projects/DIE-engine/FormatWidgets/formatswidget.ui \
    projects/DIE-engine/FormatWidgets/toolswidget.ui \
    projects/DIE-engine/StaticScan/dialogstaticscan.ui \
    projects/DIE-engine/StaticScan/dialogstaticscandirectory.ui \
    projects/DIE-engine/StaticScan/formresult.ui \
    projects/DIE-engine/StaticScan/formstaticscan.ui \
    projects/DIE-engine/StaticScan/heurwidget.ui \
    projects/DIE-engine/StaticScan/staticscanoptionswidget.ui \
    projects/DIE-engine/XAboutWidget/xaboutwidget.ui \
    projects/DIE-engine/XDataConvertorWidget/dialogxdataconvertor.ui \
    projects/DIE-engine/XDataConvertorWidget/xdataconvertorwidget.ui \
    projects/DIE-engine/XDemangleWidget/dialogdemangle.ui \
    projects/DIE-engine/XDemangleWidget/xdemanglewidget.ui \
    projects/DIE-engine/XDisasm/dialogasmsignature.ui \
    projects/DIE-engine/XDisasm/dialogdisasm.ui \
    projects/DIE-engine/XDisasm/dialogdisasmlabels.ui \
    projects/DIE-engine/XDisasm/dialogdisasmprocess.ui \
    projects/DIE-engine/XDisasm/xdisasmwidget.ui \
    projects/DIE-engine/XDisasmView/dialogmultidisasm.ui \
    projects/DIE-engine/XDisasmView/dialogmultidisasmsignature.ui \
    projects/DIE-engine/XDisasmView/xdisasmviewoptionswidget.ui \
    projects/DIE-engine/XDisasmView/xmultidisasmwidget.ui \
    projects/DIE-engine/XDynStructsWidget/dialogxdynstructs.ui \
    projects/DIE-engine/XDynStructsWidget/xdynstructsoptionswidget.ui \
    projects/DIE-engine/XDynStructsWidget/xdynstructswidget.ui \
    projects/DIE-engine/XEntropyWidget/dialogentropy.ui \
    projects/DIE-engine/XEntropyWidget/xentropywidget.ui \
    projects/DIE-engine/XExtractorWidget/dialogxextractor.ui \
    projects/DIE-engine/XExtractorWidget/xextractorwidget.ui \
    projects/DIE-engine/XFileInfo/dialogxfileinfo.ui \
    projects/DIE-engine/XFileInfo/xfileinfowidget.ui \
    projects/DIE-engine/XHashWidget/dialoghash.ui \
    projects/DIE-engine/XHashWidget/xhashwidget.ui \
    projects/DIE-engine/XHexEdit/dialoghexedit.ui \
    projects/DIE-engine/XHexView/dialoghexview.ui \
    projects/DIE-engine/XHexView/xhexviewoptionswidget.ui \
    projects/DIE-engine/XHexView/xhexviewwidget.ui \
    projects/DIE-engine/XInfoDB/xinfodboptionswidget.ui \
    projects/DIE-engine/XMIMEWidget/dialogmime.ui \
    projects/DIE-engine/XMIMEWidget/xmimewidget.ui \
    projects/DIE-engine/XMemoryMapWidget/dialogmemorymap.ui \
    projects/DIE-engine/XMemoryMapWidget/xmemorymapwidget.ui \
    projects/DIE-engine/XOnlineTools/dialogxvirustotal.ui \
    projects/DIE-engine/XOnlineTools/xonlinetoolsoptionswidget.ui \
    projects/DIE-engine/XOnlineTools/xvirustotalwidget.ui \
    projects/DIE-engine/XOptions/dialogviewcolors.ui \
    projects/DIE-engine/XOptions/xoptionswidget.ui \
    projects/DIE-engine/XShortcuts/dialogshortcuts.ui \
    projects/DIE-engine/XSymbolsWidget/dialogbookmarks.ui \
    projects/DIE-engine/XSymbolsWidget/dialogxsymbols.ui \
    projects/DIE-engine/XSymbolsWidget/xsymbolswidget.ui \
    projects/DIE-engine/XVisualizationWidget/dialogvisualization.ui \
    projects/DIE-engine/XVisualizationWidget/xvisualizationwidget.ui \
    projects/DIE-engine/archive_widget/archive_widget.ui \
    projects/DIE-engine/archive_widget/dialogarchive.ui \
    projects/DIE-engine/archive_widget/dialogshowimage.ui \
    projects/DIE-engine/archive_widget/dialogshowtext.ui \
    projects/DIE-engine/die_widget/dialogdiehexviewer.ui \
    projects/DIE-engine/die_widget/dialogdiescandirectory.ui \
    projects/DIE-engine/die_widget/dialogdiesignatures.ui \
    projects/DIE-engine/die_widget/dialogdiesignatureselapsed.ui \
    projects/DIE-engine/die_widget/die_widget.ui \
    projects/DIE-engine/die_widget/dieoptionswidget.ui \
    projects/DIE-engine/die_widget/diewidgetadvanced.ui \
    projects/DIE-engine/gui_source/dialogabout.ui \
    projects/DIE-engine/gui_source/dialogoptions.ui \
    projects/DIE-engine/gui_source/dialogselectstyle.ui \
    projects/DIE-engine/gui_source/guimainwindow.ui \
    projects/DIE-engine/lite_source/litemainwindow.ui \
    projects/DIE-engine/nfd_widget/dialognfdscan.ui \
    projects/DIE-engine/nfd_widget/dialognfdscandirectory.ui \
    projects/DIE-engine/nfd_widget/dialognfdwidgetadvanced.ui \
    projects/DIE-engine/nfd_widget/nfd_widget.ui \
    projects/DIE-engine/nfd_widget/nfdoptionswidget.ui \
    projects/DIE-engine/nfd_widget/nfdwidgetadvanced.ui \
    projects/DIE-engine/yara_widget/dialogyarawidgetadvanced.ui \
    projects/DIE-engine/yara_widget/yara_widget.ui \
    projects/DIE-engine/yara_widget/yarawidgetadvanced.ui \
    projects/Nauz-File-Detector/Controls/dialogbits8.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogdatainspector.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogdump.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogeditstring.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogfindtext.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialoggotoaddress.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialoghexsignature.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogremove.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogresize.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogsearch.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogsearchprocess.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogshowdata.ui \
    projects/Nauz-File-Detector/FormatDialogs/dialogtextinfo.ui \
    projects/Nauz-File-Detector/FormatDialogs/xdialogprocess.ui \
    projects/Nauz-File-Detector/StaticScan/dialogstaticscan.ui \
    projects/Nauz-File-Detector/StaticScan/dialogstaticscandirectory.ui \
    projects/Nauz-File-Detector/StaticScan/formresult.ui \
    projects/Nauz-File-Detector/StaticScan/formstaticscan.ui \
    projects/Nauz-File-Detector/StaticScan/heurwidget.ui \
    projects/Nauz-File-Detector/StaticScan/staticscanoptionswidget.ui \
    projects/Nauz-File-Detector/XAboutWidget/xaboutwidget.ui \
    projects/Nauz-File-Detector/XInfoDB/xinfodboptionswidget.ui \
    projects/Nauz-File-Detector/XOnlineTools/dialogxvirustotal.ui \
    projects/Nauz-File-Detector/XOnlineTools/xonlinetoolsoptionswidget.ui \
    projects/Nauz-File-Detector/XOnlineTools/xvirustotalwidget.ui \
    projects/Nauz-File-Detector/XOptions/dialogviewcolors.ui \
    projects/Nauz-File-Detector/XOptions/xoptionswidget.ui \
    projects/Nauz-File-Detector/XShortcuts/dialogshortcuts.ui \
    projects/Nauz-File-Detector/XSymbolsWidget/dialogbookmarks.ui \
    projects/Nauz-File-Detector/XSymbolsWidget/dialogxsymbols.ui \
    projects/Nauz-File-Detector/XSymbolsWidget/xsymbolswidget.ui \
    projects/Nauz-File-Detector/gui_source/dialogabout.ui \
    projects/Nauz-File-Detector/gui_source/dialogoptions.ui \
    projects/Nauz-File-Detector/gui_source/guimainwindow.ui \
    projects/Nauz-File-Detector/nfd_widget/dialognfdscan.ui \
    projects/Nauz-File-Detector/nfd_widget/dialognfdscandirectory.ui \
    projects/Nauz-File-Detector/nfd_widget/dialognfdwidgetadvanced.ui \
    projects/Nauz-File-Detector/nfd_widget/nfd_widget.ui \
    projects/Nauz-File-Detector/nfd_widget/nfdoptionswidget.ui \
    projects/Nauz-File-Detector/nfd_widget/nfdwidgetadvanced.ui \
    projects/PDBRipper/XAboutWidget/xaboutwidget.ui \
    projects/PDBRipper/XOptions/dialogviewcolors.ui \
    projects/PDBRipper/XOptions/xoptionswidget.ui \
    projects/PDBRipper/XShortcuts/dialogshortcuts.ui \
    projects/PDBRipper/gui_source/dialogabout.ui \
    projects/PDBRipper/gui_source/dialogexport.ui \
    projects/PDBRipper/gui_source/dialogoptions.ui \
    projects/PDBRipper/gui_source/dialogprocess.ui \
    projects/PDBRipper/gui_source/guimainwindow.ui \
    projects/XOpcodeCalc/Controls/dialogbits8.ui \
    projects/XOpcodeCalc/XAboutWidget/xaboutwidget.ui \
    projects/XOpcodeCalc/XOptions/dialogviewcolors.ui \
    projects/XOpcodeCalc/XOptions/xoptionswidget.ui \
    projects/XOpcodeCalc/XShortcuts/dialogshortcuts.ui \
    projects/XOpcodeCalc/gui_source/dialogabout.ui \
    projects/XOpcodeCalc/gui_source/dialogoptions.ui \
    projects/XOpcodeCalc/gui_source/guimainwindow.ui

SOURCES += \
    projects/DIE-engine/Controls/dialogbits8.cpp \
    projects/DIE-engine/Controls/subclassofqstyleditemdelegate.cpp \
    projects/DIE-engine/Controls/xabstracttableview.cpp \
    projects/DIE-engine/Controls/xcomboboxex.cpp \
    projects/DIE-engine/Controls/xdatetimeeditx.cpp \
    projects/DIE-engine/Controls/xdevicetableeditview.cpp \
    projects/DIE-engine/Controls/xdevicetableview.cpp \
    projects/DIE-engine/Controls/xheaderview.cpp \
    projects/DIE-engine/Controls/xhtml.cpp \
    projects/DIE-engine/Controls/xlineedithex.cpp \
    projects/DIE-engine/Controls/xlineeditvalidator.cpp \
    projects/DIE-engine/Controls/xsortfilterproxymodel.cpp \
    projects/DIE-engine/Controls/xtableview.cpp \
    projects/DIE-engine/FormatDialogs/dialogdatainspector.cpp \
    projects/DIE-engine/FormatDialogs/dialogdumpprocess.cpp \
    projects/DIE-engine/FormatDialogs/dialogeditstring.cpp \
    projects/DIE-engine/FormatDialogs/dialogfindtext.cpp \
    projects/DIE-engine/FormatDialogs/dialoggotoaddress.cpp \
    projects/DIE-engine/FormatDialogs/dialoghexsignature.cpp \
    projects/DIE-engine/FormatDialogs/dialogremove.cpp \
    projects/DIE-engine/FormatDialogs/dialogresize.cpp \
    projects/DIE-engine/FormatDialogs/dialogsearch.cpp \
    projects/DIE-engine/FormatDialogs/dialogsearchprocess.cpp \
    projects/DIE-engine/FormatDialogs/dialogshowdata.cpp \
    projects/DIE-engine/FormatDialogs/dialogtextinfo.cpp \
    projects/DIE-engine/FormatDialogs/dumpprocess.cpp \
    projects/DIE-engine/FormatDialogs/searchprocess.cpp \
    projects/DIE-engine/FormatDialogs/xdialogprocess.cpp \
    projects/DIE-engine/FormatWidgets/Binary/binary_defs.cpp \
    projects/DIE-engine/FormatWidgets/Binary/binarywidget.cpp \
    projects/DIE-engine/FormatWidgets/Binary/dialogbinary.cpp \
    projects/DIE-engine/FormatWidgets/DEX/dex_defs.cpp \
    projects/DIE-engine/FormatWidgets/DEX/dexprocessdata.cpp \
    projects/DIE-engine/FormatWidgets/DEX/dexsectionheaderwidget.cpp \
    projects/DIE-engine/FormatWidgets/DEX/dexwidget.cpp \
    projects/DIE-engine/FormatWidgets/DEX/dialogdex.cpp \
    projects/DIE-engine/FormatWidgets/ELF/dialogelf.cpp \
    projects/DIE-engine/FormatWidgets/ELF/elf_defs.cpp \
    projects/DIE-engine/FormatWidgets/ELF/elfprocessdata.cpp \
    projects/DIE-engine/FormatWidgets/ELF/elfsectionheaderwidget.cpp \
    projects/DIE-engine/FormatWidgets/ELF/elfwidget.cpp \
    projects/DIE-engine/FormatWidgets/LE/dialogle.cpp \
    projects/DIE-engine/FormatWidgets/LE/le_defs.cpp \
    projects/DIE-engine/FormatWidgets/LE/leprocessdata.cpp \
    projects/DIE-engine/FormatWidgets/LE/lesectionheaderwidget.cpp \
    projects/DIE-engine/FormatWidgets/LE/lewidget.cpp \
    projects/DIE-engine/FormatWidgets/MACH/dialogmach.cpp \
    projects/DIE-engine/FormatWidgets/MACH/mach_defs.cpp \
    projects/DIE-engine/FormatWidgets/MACH/machprocessdata.cpp \
    projects/DIE-engine/FormatWidgets/MACH/machsectionheaderwidget.cpp \
    projects/DIE-engine/FormatWidgets/MACH/machwidget.cpp \
    projects/DIE-engine/FormatWidgets/MACHOFAT/dialogmachofat.cpp \
    projects/DIE-engine/FormatWidgets/MACHOFAT/machofatwidget.cpp \
    projects/DIE-engine/FormatWidgets/MSDOS/dialogmsdos.cpp \
    projects/DIE-engine/FormatWidgets/MSDOS/msdos_defs.cpp \
    projects/DIE-engine/FormatWidgets/MSDOS/msdoswidget.cpp \
    projects/DIE-engine/FormatWidgets/MultiSearch/dialogmultisearchprocess.cpp \
    projects/DIE-engine/FormatWidgets/MultiSearch/multisearch.cpp \
    projects/DIE-engine/FormatWidgets/NE/dialogne.cpp \
    projects/DIE-engine/FormatWidgets/NE/ne_defs.cpp \
    projects/DIE-engine/FormatWidgets/NE/neprocessdata.cpp \
    projects/DIE-engine/FormatWidgets/NE/nesectionheaderwidget.cpp \
    projects/DIE-engine/FormatWidgets/NE/newidget.cpp \
    projects/DIE-engine/FormatWidgets/PDF/dialogpdf.cpp \
    projects/DIE-engine/FormatWidgets/PDF/pdf_defs.cpp \
    projects/DIE-engine/FormatWidgets/PDF/pdfwidget.cpp \
    projects/DIE-engine/FormatWidgets/PE/dialogpe.cpp \
    projects/DIE-engine/FormatWidgets/PE/pe_defs.cpp \
    projects/DIE-engine/FormatWidgets/PE/peprocessdata.cpp \
    projects/DIE-engine/FormatWidgets/PE/pesectionheaderwidget.cpp \
    projects/DIE-engine/FormatWidgets/PE/petoolswidget.cpp \
    projects/DIE-engine/FormatWidgets/PE/pewidget.cpp \
    projects/DIE-engine/FormatWidgets/SearchSignatures/dialogsearchsignatures.cpp \
    projects/DIE-engine/FormatWidgets/SearchSignatures/searchsignaturesoptionswidget.cpp \
    projects/DIE-engine/FormatWidgets/SearchSignatures/searchsignatureswidget.cpp \
    projects/DIE-engine/FormatWidgets/SearchStrings/dialogsearchstrings.cpp \
    projects/DIE-engine/FormatWidgets/SearchStrings/searchstringswidget.cpp \
    projects/DIE-engine/FormatWidgets/SearchValues/dialogsearchvalues.cpp \
    projects/DIE-engine/FormatWidgets/SearchValues/searchvalueswidget.cpp \
    projects/DIE-engine/FormatWidgets/dialogmodelinfo.cpp \
    projects/DIE-engine/FormatWidgets/dialogprocessdata.cpp \
    projects/DIE-engine/FormatWidgets/dialogsectionheader.cpp \
    projects/DIE-engine/FormatWidgets/formatswidget.cpp \
    projects/DIE-engine/FormatWidgets/formatwidget.cpp \
    projects/DIE-engine/FormatWidgets/invwidget.cpp \
    projects/DIE-engine/FormatWidgets/processdata.cpp \
    projects/DIE-engine/FormatWidgets/toolswidget.cpp \
    projects/DIE-engine/Formats/audio/xmp3.cpp \
    projects/DIE-engine/Formats/exec/xamigahunk.cpp \
    projects/DIE-engine/Formats/exec/xcom.cpp \
    projects/DIE-engine/Formats/exec/xelf.cpp \
    projects/DIE-engine/Formats/exec/xle.cpp \
    projects/DIE-engine/Formats/exec/xmach.cpp \
    projects/DIE-engine/Formats/exec/xmsdos.cpp \
    projects/DIE-engine/Formats/exec/xne.cpp \
    projects/DIE-engine/Formats/exec/xpe.cpp \
    projects/DIE-engine/Formats/images/xbmp.cpp \
    projects/DIE-engine/Formats/images/xgif.cpp \
    projects/DIE-engine/Formats/images/xicon.cpp \
    projects/DIE-engine/Formats/images/xjpeg.cpp \
    projects/DIE-engine/Formats/images/xpng.cpp \
    projects/DIE-engine/Formats/images/xtiff.cpp \
    projects/DIE-engine/Formats/subdevice.cpp \
    projects/DIE-engine/Formats/video/xmp4.cpp \
    projects/DIE-engine/Formats/video/xriff.cpp \
    projects/DIE-engine/Formats/xbinary.cpp \
    projects/DIE-engine/Formats/xdataconvertor.cpp \
    projects/DIE-engine/Formats/xformats.cpp \
    projects/DIE-engine/Formats/xiodevice.cpp \
    projects/DIE-engine/SpecAbstract/signatures.cpp \
    projects/DIE-engine/SpecAbstract/specabstract.cpp \
    projects/DIE-engine/SpecAbstract/staticscan.cpp \
    projects/DIE-engine/StaticScan/dialogstaticscan.cpp \
    projects/DIE-engine/StaticScan/dialogstaticscandirectory.cpp \
    projects/DIE-engine/StaticScan/dialogstaticscanprocess.cpp \
    projects/DIE-engine/StaticScan/formresult.cpp \
    projects/DIE-engine/StaticScan/formstaticscan.cpp \
    projects/DIE-engine/StaticScan/heurwidget.cpp \
    projects/DIE-engine/StaticScan/staticscan.cpp \
    projects/DIE-engine/StaticScan/staticscanitem.cpp \
    projects/DIE-engine/StaticScan/staticscanitemmodel.cpp \
    projects/DIE-engine/StaticScan/staticscanoptionswidget.cpp \
    projects/DIE-engine/XAboutWidget/xaboutwidget.cpp \
    projects/DIE-engine/XArchive/x_ar.cpp \
    projects/DIE-engine/XArchive/xapk.cpp \
    projects/DIE-engine/XArchive/xapks.cpp \
    projects/DIE-engine/XArchive/xarchive.cpp \
    projects/DIE-engine/XArchive/xarchives.cpp \
    projects/DIE-engine/XArchive/xcab.cpp \
    projects/DIE-engine/XArchive/xcompress.cpp \
    projects/DIE-engine/XArchive/xcompresseddevice.cpp \
    projects/DIE-engine/XArchive/xdeb.cpp \
    projects/DIE-engine/XArchive/xdos16.cpp \
    projects/DIE-engine/XArchive/xgzip.cpp \
    projects/DIE-engine/XArchive/xipa.cpp \
    projects/DIE-engine/XArchive/xjar.cpp \
    projects/DIE-engine/XArchive/xlha.cpp \
    projects/DIE-engine/XArchive/xmachofat.cpp \
    projects/DIE-engine/XArchive/xnpm.cpp \
    projects/DIE-engine/XArchive/xrar.cpp \
    projects/DIE-engine/XArchive/xsevenzip.cpp \
    projects/DIE-engine/XArchive/xtar.cpp \
    projects/DIE-engine/XArchive/xtgz.cpp \
    projects/DIE-engine/XArchive/xzip.cpp \
    projects/DIE-engine/XArchive/xzlib.cpp \
    projects/DIE-engine/XCapstone/xcapstone.cpp \
    projects/DIE-engine/XCppfilt/xcppfilt.cpp \
    projects/DIE-engine/XDEX/xandroidbinary.cpp \
    projects/DIE-engine/XDEX/xdex.cpp \
    projects/DIE-engine/XDataConvertorWidget/dialogxdataconvertor.cpp \
    projects/DIE-engine/XDataConvertorWidget/dialogxdataconvertorprocess.cpp \
    projects/DIE-engine/XDataConvertorWidget/xdataconvertorwidget.cpp \
    projects/DIE-engine/XDecompiler/xdecompiler.cpp \
    projects/DIE-engine/XDemangle/xdemangle.cpp \
    projects/DIE-engine/XDemangleWidget/dialogdemangle.cpp \
    projects/DIE-engine/XDemangleWidget/xdemanglewidget.cpp \
    projects/DIE-engine/XDisasm/dialogasmsignature.cpp \
    projects/DIE-engine/XDisasm/dialogdisasm.cpp \
    projects/DIE-engine/XDisasm/dialogdisasmlabels.cpp \
    projects/DIE-engine/XDisasm/dialogdisasmprocess.cpp \
    projects/DIE-engine/XDisasm/xdisasm.cpp \
    projects/DIE-engine/XDisasm/xdisasmmodel.cpp \
    projects/DIE-engine/XDisasm/xdisasmwidget.cpp \
    projects/DIE-engine/XDisasmView/dialogmultidisasm.cpp \
    projects/DIE-engine/XDisasmView/dialogmultidisasmsignature.cpp \
    projects/DIE-engine/XDisasmView/xdisasmview.cpp \
    projects/DIE-engine/XDisasmView/xdisasmviewoptionswidget.cpp \
    projects/DIE-engine/XDisasmView/xmultidisasmwidget.cpp \
    projects/DIE-engine/XDynStructsEngine/xdynstructsengine.cpp \
    projects/DIE-engine/XDynStructsWidget/dialogxdynstructs.cpp \
    projects/DIE-engine/XDynStructsWidget/xdynstructsoptionswidget.cpp \
    projects/DIE-engine/XDynStructsWidget/xdynstructswidget.cpp \
    projects/DIE-engine/XEntropyWidget/dialogentropy.cpp \
    projects/DIE-engine/XEntropyWidget/dialogentropyprocess.cpp \
    projects/DIE-engine/XEntropyWidget/entropyprocess.cpp \
    projects/DIE-engine/XEntropyWidget/xentropywidget.cpp \
    projects/DIE-engine/XExtractor/xextractor.cpp \
    projects/DIE-engine/XExtractorWidget/dialogextractorprocess.cpp \
    projects/DIE-engine/XExtractorWidget/dialogxextractor.cpp \
    projects/DIE-engine/XExtractorWidget/xextractorwidget.cpp \
    projects/DIE-engine/XFileInfo/dialogxfileinfo.cpp \
    projects/DIE-engine/XFileInfo/dialogxfileinfoprocess.cpp \
    projects/DIE-engine/XFileInfo/xfileinfo.cpp \
    projects/DIE-engine/XFileInfo/xfileinfoitem.cpp \
    projects/DIE-engine/XFileInfo/xfileinfomodel.cpp \
    projects/DIE-engine/XFileInfo/xfileinfowidget.cpp \
    projects/DIE-engine/XGithub/xgithub.cpp \
    projects/DIE-engine/XHashWidget/dialoghash.cpp \
    projects/DIE-engine/XHashWidget/dialoghashprocess.cpp \
    projects/DIE-engine/XHashWidget/hashprocess.cpp \
    projects/DIE-engine/XHashWidget/xhashwidget.cpp \
    projects/DIE-engine/XHexEdit/dialoghexedit.cpp \
    projects/DIE-engine/XHexEdit/xhexedit.cpp \
    projects/DIE-engine/XHexView/dialoghexview.cpp \
    projects/DIE-engine/XHexView/xhexview.cpp \
    projects/DIE-engine/XHexView/xhexviewoptionswidget.cpp \
    projects/DIE-engine/XHexView/xhexviewwidget.cpp \
    projects/DIE-engine/XInfoDB/dialogxinfodbtransferprocess.cpp \
    projects/DIE-engine/XInfoDB/xinfodb.cpp \
    projects/DIE-engine/XInfoDB/xinfodboptionswidget.cpp \
    projects/DIE-engine/XInfoDB/xinfodbtransfer.cpp \
    projects/DIE-engine/XInfoDB/xinfomenu.cpp \
    projects/DIE-engine/XMIME/xmime.cpp \
    projects/DIE-engine/XMIMEWidget/dialogmime.cpp \
    projects/DIE-engine/XMIMEWidget/xmimewidget.cpp \
    projects/DIE-engine/XMemoryMapWidget/dialogmemorymap.cpp \
    projects/DIE-engine/XMemoryMapWidget/xmemorymapwidget.cpp \
    projects/DIE-engine/XOnlineTools/dialogxvirustotal.cpp \
    projects/DIE-engine/XOnlineTools/xonlinetools.cpp \
    projects/DIE-engine/XOnlineTools/xonlinetoolsdialogprocess.cpp \
    projects/DIE-engine/XOnlineTools/xonlinetoolsoptionswidget.cpp \
    projects/DIE-engine/XOnlineTools/xvirustotal.cpp \
    projects/DIE-engine/XOnlineTools/xvirustotalwidget.cpp \
    projects/DIE-engine/XOptions/codecs/codec_cp437.cpp \
    projects/DIE-engine/XOptions/dialogviewcolors.cpp \
    projects/DIE-engine/XOptions/xoptions.cpp \
    projects/DIE-engine/XOptions/xoptionswidget.cpp \
    projects/DIE-engine/XPDF/xpdf.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_abstract_legend.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_abstract_scale.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_abstract_scale_draw.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_abstract_slider.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_analog_clock.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_arrow_button.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_bezier.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_clipper.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_color_map.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_column_symbol.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_compass.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_compass_rose.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_counter.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_curve_fitter.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_date.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_date_scale_draw.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_date_scale_engine.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_dial.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_dial_needle.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_dyngrid_layout.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_event_pattern.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_graphic.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_interval.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_interval_symbol.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_knob.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_legend.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_legend_data.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_legend_label.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_magnifier.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_math.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_matrix_raster_data.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_null_paintdevice.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_painter.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_painter_command.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_panner.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_picker.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_picker_machine.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_pixel_matrix.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_abstract_barchart.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_abstract_canvas.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_axis.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_barchart.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_canvas.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_curve.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_dict.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_directpainter.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_glcanvas.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_graphicitem.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_grid.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_histogram.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_intervalcurve.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_item.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_layout.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_legenditem.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_magnifier.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_marker.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_multi_barchart.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_opengl_canvas.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_panner.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_picker.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_rasteritem.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_renderer.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_rescaler.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_scaleitem.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_seriesitem.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_shapeitem.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_spectrocurve.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_spectrogram.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_svgitem.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_textlabel.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_tradingcurve.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_vectorfield.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_zoneitem.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_plot_zoomer.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_point_3d.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_point_data.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_point_mapper.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_point_polar.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_canvas.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_curve.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_fitter.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_grid.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_item.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_itemdict.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_layout.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_magnifier.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_marker.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_panner.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_picker.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_plot.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_renderer.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_polar_spectrogram.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_raster_data.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_round_scale_draw.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_sampling_thread.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_scale_div.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_scale_draw.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_scale_engine.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_scale_map.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_scale_widget.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_series_data.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_slider.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_spline.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_spline_basis.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_spline_cubic.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_spline_curve_fitter.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_spline_local.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_spline_parametrization.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_spline_pleasing.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_spline_polynomial.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_symbol.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_system_clock.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_text.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_text_engine.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_text_label.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_thermo.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_transform.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_vectorfield_symbol.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_weeding_curve_fitter.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_wheel.cpp \
    projects/DIE-engine/XQwt/3rdparty/qwt/src/qwt_widget_overlay.cpp \
    projects/DIE-engine/XScanEngine/scanitem.cpp \
    projects/DIE-engine/XScanEngine/scanitemmodel.cpp \
    projects/DIE-engine/XScanEngine/xscanengine.cpp \
    projects/DIE-engine/XShortcuts/dialogshortcuts.cpp \
    projects/DIE-engine/XShortcuts/xshortcuts.cpp \
    projects/DIE-engine/XShortcuts/xshortcutsdialog.cpp \
    projects/DIE-engine/XShortcuts/xshortcutstscrollarea.cpp \
    projects/DIE-engine/XShortcuts/xshortcutswidget.cpp \
    projects/DIE-engine/XSingleApplication/xsingleapplication.cpp \
    projects/DIE-engine/XSymbolsWidget/dialogbookmarks.cpp \
    projects/DIE-engine/XSymbolsWidget/dialogxsymbols.cpp \
    projects/DIE-engine/XSymbolsWidget/xsymbolswidget.cpp \
    projects/DIE-engine/XUpdate/xupdate.cpp \
    projects/DIE-engine/XVisualizationWidget/dialogvisualization.cpp \
    projects/DIE-engine/XVisualizationWidget/dialogvisualizationprocess.cpp \
    projects/DIE-engine/XVisualizationWidget/xfilearrow.cpp \
    projects/DIE-engine/XVisualizationWidget/xfiledescription.cpp \
    projects/DIE-engine/XVisualizationWidget/xfileimage.cpp \
    projects/DIE-engine/XVisualizationWidget/xvisualization.cpp \
    projects/DIE-engine/XVisualizationWidget/xvisualizationimage.cpp \
    projects/DIE-engine/XVisualizationWidget/xvisualizationwidget.cpp \
    projects/DIE-engine/XYara/xyara.cpp \
    projects/DIE-engine/archive_widget/archive_widget.cpp \
    projects/DIE-engine/archive_widget/createviewmodelprocess.cpp \
    projects/DIE-engine/archive_widget/dialogarchive.cpp \
    projects/DIE-engine/archive_widget/dialogcreateviewmodel.cpp \
    projects/DIE-engine/archive_widget/dialogshowimage.cpp \
    projects/DIE-engine/archive_widget/dialogshowtext.cpp \
    projects/DIE-engine/archive_widget/dialogunpackfile.cpp \
    projects/DIE-engine/archive_widget/unpackfileprocess.cpp \
    projects/DIE-engine/console_source/consoleoutput.cpp \
    projects/DIE-engine/console_source/main_console.cpp \
    projects/DIE-engine/die_script/amiga_script.cpp \
    projects/DIE-engine/die_script/apk_script.cpp \
    projects/DIE-engine/die_script/archive_script.cpp \
    projects/DIE-engine/die_script/binary_script.cpp \
    projects/DIE-engine/die_script/com_script.cpp \
    projects/DIE-engine/die_script/dex_script.cpp \
    projects/DIE-engine/die_script/die_script.cpp \
    projects/DIE-engine/die_script/die_scriptengine.cpp \
    projects/DIE-engine/die_script/elf_script.cpp \
    projects/DIE-engine/die_script/global_script.cpp \
    projects/DIE-engine/die_script/ipa_script.cpp \
    projects/DIE-engine/die_script/jar_script.cpp \
    projects/DIE-engine/die_script/le_script.cpp \
    projects/DIE-engine/die_script/lx_script.cpp \
    projects/DIE-engine/die_script/mach_script.cpp \
    projects/DIE-engine/die_script/msdos_script.cpp \
    projects/DIE-engine/die_script/ne_script.cpp \
    projects/DIE-engine/die_script/npm_script.cpp \
    projects/DIE-engine/die_script/pe_script.cpp \
    projects/DIE-engine/die_script/util_script.cpp \
    projects/DIE-engine/die_script/xscriptengine.cpp \
    projects/DIE-engine/die_script/zip_script.cpp \
    projects/DIE-engine/die_widget/dialogdiehexviewer.cpp \
    projects/DIE-engine/die_widget/dialogdiescandirectory.cpp \
    projects/DIE-engine/die_widget/dialogdiescanprocess.cpp \
    projects/DIE-engine/die_widget/dialogdiesignatures.cpp \
    projects/DIE-engine/die_widget/dialogdiesignatureselapsed.cpp \
    projects/DIE-engine/die_widget/die_highlighter.cpp \
    projects/DIE-engine/die_widget/die_signatureedit.cpp \
    projects/DIE-engine/die_widget/die_widget.cpp \
    projects/DIE-engine/die_widget/dieoptionswidget.cpp \
    projects/DIE-engine/die_widget/diewidgetadvanced.cpp \
    projects/DIE-engine/gui_source/dialogabout.cpp \
    projects/DIE-engine/gui_source/dialogoptions.cpp \
    projects/DIE-engine/gui_source/dialogselectstyle.cpp \
    projects/DIE-engine/gui_source/guimainwindow.cpp \
    projects/DIE-engine/gui_source/main_gui.cpp \
    projects/DIE-engine/lite_source/litemainwindow.cpp \
    projects/DIE-engine/lite_source/main_lite.cpp \
    projects/DIE-engine/nfd_widget/dialognfdscan.cpp \
    projects/DIE-engine/nfd_widget/dialognfdscandirectory.cpp \
    projects/DIE-engine/nfd_widget/dialognfdscanprocess.cpp \
    projects/DIE-engine/nfd_widget/dialognfdwidgetadvanced.cpp \
    projects/DIE-engine/nfd_widget/nfd_widget.cpp \
    projects/DIE-engine/nfd_widget/nfdoptionswidget.cpp \
    projects/DIE-engine/nfd_widget/nfdwidgetadvanced.cpp \
    projects/DIE-engine/yara_widget/dialogyarawidgetadvanced.cpp \
    projects/DIE-engine/yara_widget/xyaradialogprocess.cpp \
    projects/DIE-engine/yara_widget/yara_widget.cpp \
    projects/DIE-engine/yara_widget/yarawidgetadvanced.cpp \
    projects/Nauz-File-Detector/Controls/dialogbits8.cpp \
    projects/Nauz-File-Detector/Controls/subclassofqstyleditemdelegate.cpp \
    projects/Nauz-File-Detector/Controls/xabstracttableview.cpp \
    projects/Nauz-File-Detector/Controls/xcomboboxex.cpp \
    projects/Nauz-File-Detector/Controls/xdatetimeeditx.cpp \
    projects/Nauz-File-Detector/Controls/xdevicetableeditview.cpp \
    projects/Nauz-File-Detector/Controls/xdevicetableview.cpp \
    projects/Nauz-File-Detector/Controls/xheaderview.cpp \
    projects/Nauz-File-Detector/Controls/xhtml.cpp \
    projects/Nauz-File-Detector/Controls/xlineedithex.cpp \
    projects/Nauz-File-Detector/Controls/xlineeditvalidator.cpp \
    projects/Nauz-File-Detector/Controls/xsortfilterproxymodel.cpp \
    projects/Nauz-File-Detector/Controls/xtableview.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogdatainspector.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogdumpprocess.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogeditstring.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogfindtext.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialoggotoaddress.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialoghexsignature.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogremove.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogresize.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogsearch.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogsearchprocess.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogshowdata.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dialogtextinfo.cpp \
    projects/Nauz-File-Detector/FormatDialogs/dumpprocess.cpp \
    projects/Nauz-File-Detector/FormatDialogs/searchprocess.cpp \
    projects/Nauz-File-Detector/FormatDialogs/xdialogprocess.cpp \
    projects/Nauz-File-Detector/Formats/audio/xmp3.cpp \
    projects/Nauz-File-Detector/Formats/exec/xamigahunk.cpp \
    projects/Nauz-File-Detector/Formats/exec/xcom.cpp \
    projects/Nauz-File-Detector/Formats/exec/xelf.cpp \
    projects/Nauz-File-Detector/Formats/exec/xle.cpp \
    projects/Nauz-File-Detector/Formats/exec/xmach.cpp \
    projects/Nauz-File-Detector/Formats/exec/xmsdos.cpp \
    projects/Nauz-File-Detector/Formats/exec/xne.cpp \
    projects/Nauz-File-Detector/Formats/exec/xpe.cpp \
    projects/Nauz-File-Detector/Formats/images/xbmp.cpp \
    projects/Nauz-File-Detector/Formats/images/xgif.cpp \
    projects/Nauz-File-Detector/Formats/images/xicon.cpp \
    projects/Nauz-File-Detector/Formats/images/xjpeg.cpp \
    projects/Nauz-File-Detector/Formats/images/xpng.cpp \
    projects/Nauz-File-Detector/Formats/images/xtiff.cpp \
    projects/Nauz-File-Detector/Formats/subdevice.cpp \
    projects/Nauz-File-Detector/Formats/video/xmp4.cpp \
    projects/Nauz-File-Detector/Formats/video/xriff.cpp \
    projects/Nauz-File-Detector/Formats/xbinary.cpp \
    projects/Nauz-File-Detector/Formats/xdataconvertor.cpp \
    projects/Nauz-File-Detector/Formats/xformats.cpp \
    projects/Nauz-File-Detector/Formats/xiodevice.cpp \
    projects/Nauz-File-Detector/SpecAbstract/signatures.cpp \
    projects/Nauz-File-Detector/SpecAbstract/specabstract.cpp \
    projects/Nauz-File-Detector/SpecAbstract/staticscan.cpp \
    projects/Nauz-File-Detector/StaticScan/dialogstaticscan.cpp \
    projects/Nauz-File-Detector/StaticScan/dialogstaticscandirectory.cpp \
    projects/Nauz-File-Detector/StaticScan/dialogstaticscanprocess.cpp \
    projects/Nauz-File-Detector/StaticScan/formresult.cpp \
    projects/Nauz-File-Detector/StaticScan/formstaticscan.cpp \
    projects/Nauz-File-Detector/StaticScan/heurwidget.cpp \
    projects/Nauz-File-Detector/StaticScan/staticscan.cpp \
    projects/Nauz-File-Detector/StaticScan/staticscanitem.cpp \
    projects/Nauz-File-Detector/StaticScan/staticscanitemmodel.cpp \
    projects/Nauz-File-Detector/StaticScan/staticscanoptionswidget.cpp \
    projects/Nauz-File-Detector/XAboutWidget/xaboutwidget.cpp \
    projects/Nauz-File-Detector/XArchive/x_ar.cpp \
    projects/Nauz-File-Detector/XArchive/xapk.cpp \
    projects/Nauz-File-Detector/XArchive/xapks.cpp \
    projects/Nauz-File-Detector/XArchive/xarchive.cpp \
    projects/Nauz-File-Detector/XArchive/xarchives.cpp \
    projects/Nauz-File-Detector/XArchive/xcab.cpp \
    projects/Nauz-File-Detector/XArchive/xcompress.cpp \
    projects/Nauz-File-Detector/XArchive/xcompresseddevice.cpp \
    projects/Nauz-File-Detector/XArchive/xdeb.cpp \
    projects/Nauz-File-Detector/XArchive/xdos16.cpp \
    projects/Nauz-File-Detector/XArchive/xgzip.cpp \
    projects/Nauz-File-Detector/XArchive/xipa.cpp \
    projects/Nauz-File-Detector/XArchive/xjar.cpp \
    projects/Nauz-File-Detector/XArchive/xlha.cpp \
    projects/Nauz-File-Detector/XArchive/xmachofat.cpp \
    projects/Nauz-File-Detector/XArchive/xnpm.cpp \
    projects/Nauz-File-Detector/XArchive/xrar.cpp \
    projects/Nauz-File-Detector/XArchive/xsevenzip.cpp \
    projects/Nauz-File-Detector/XArchive/xtar.cpp \
    projects/Nauz-File-Detector/XArchive/xtgz.cpp \
    projects/Nauz-File-Detector/XArchive/xzip.cpp \
    projects/Nauz-File-Detector/XArchive/xzlib.cpp \
    projects/Nauz-File-Detector/XCapstone/xcapstone.cpp \
    projects/Nauz-File-Detector/XDEX/xandroidbinary.cpp \
    projects/Nauz-File-Detector/XDEX/xdex.cpp \
    projects/Nauz-File-Detector/XExtractor/xextractor.cpp \
    projects/Nauz-File-Detector/XGithub/xgithub.cpp \
    projects/Nauz-File-Detector/XInfoDB/dialogxinfodbtransferprocess.cpp \
    projects/Nauz-File-Detector/XInfoDB/xinfodb.cpp \
    projects/Nauz-File-Detector/XInfoDB/xinfodboptionswidget.cpp \
    projects/Nauz-File-Detector/XInfoDB/xinfodbtransfer.cpp \
    projects/Nauz-File-Detector/XInfoDB/xinfomenu.cpp \
    projects/Nauz-File-Detector/XOnlineTools/dialogxvirustotal.cpp \
    projects/Nauz-File-Detector/XOnlineTools/xonlinetools.cpp \
    projects/Nauz-File-Detector/XOnlineTools/xonlinetoolsdialogprocess.cpp \
    projects/Nauz-File-Detector/XOnlineTools/xonlinetoolsoptionswidget.cpp \
    projects/Nauz-File-Detector/XOnlineTools/xvirustotal.cpp \
    projects/Nauz-File-Detector/XOnlineTools/xvirustotalwidget.cpp \
    projects/Nauz-File-Detector/XOptions/codecs/codec_cp437.cpp \
    projects/Nauz-File-Detector/XOptions/dialogviewcolors.cpp \
    projects/Nauz-File-Detector/XOptions/xoptions.cpp \
    projects/Nauz-File-Detector/XOptions/xoptionswidget.cpp \
    projects/Nauz-File-Detector/XPDF/xpdf.cpp \
    projects/Nauz-File-Detector/XScanEngine/scanitem.cpp \
    projects/Nauz-File-Detector/XScanEngine/scanitemmodel.cpp \
    projects/Nauz-File-Detector/XScanEngine/xscanengine.cpp \
    projects/Nauz-File-Detector/XShortcuts/dialogshortcuts.cpp \
    projects/Nauz-File-Detector/XShortcuts/xshortcuts.cpp \
    projects/Nauz-File-Detector/XShortcuts/xshortcutsdialog.cpp \
    projects/Nauz-File-Detector/XShortcuts/xshortcutstscrollarea.cpp \
    projects/Nauz-File-Detector/XShortcuts/xshortcutswidget.cpp \
    projects/Nauz-File-Detector/XSymbolsWidget/dialogbookmarks.cpp \
    projects/Nauz-File-Detector/XSymbolsWidget/dialogxsymbols.cpp \
    projects/Nauz-File-Detector/XSymbolsWidget/xsymbolswidget.cpp \
    projects/Nauz-File-Detector/XUpdate/xupdate.cpp \
    projects/Nauz-File-Detector/console_source/main_console.cpp \
    projects/Nauz-File-Detector/gui_source/dialogabout.cpp \
    projects/Nauz-File-Detector/gui_source/dialogoptions.cpp \
    projects/Nauz-File-Detector/gui_source/guimainwindow.cpp \
    projects/Nauz-File-Detector/gui_source/main_gui.cpp \
    projects/Nauz-File-Detector/nfd_widget/dialognfdscan.cpp \
    projects/Nauz-File-Detector/nfd_widget/dialognfdscandirectory.cpp \
    projects/Nauz-File-Detector/nfd_widget/dialognfdscanprocess.cpp \
    projects/Nauz-File-Detector/nfd_widget/dialognfdwidgetadvanced.cpp \
    projects/Nauz-File-Detector/nfd_widget/nfd_widget.cpp \
    projects/Nauz-File-Detector/nfd_widget/nfdoptionswidget.cpp \
    projects/Nauz-File-Detector/nfd_widget/nfdwidgetadvanced.cpp \
    projects/PDBRipper/Formats/audio/xmp3.cpp \
    projects/PDBRipper/Formats/exec/xamigahunk.cpp \
    projects/PDBRipper/Formats/exec/xcom.cpp \
    projects/PDBRipper/Formats/exec/xelf.cpp \
    projects/PDBRipper/Formats/exec/xle.cpp \
    projects/PDBRipper/Formats/exec/xmach.cpp \
    projects/PDBRipper/Formats/exec/xmsdos.cpp \
    projects/PDBRipper/Formats/exec/xne.cpp \
    projects/PDBRipper/Formats/exec/xpe.cpp \
    projects/PDBRipper/Formats/images/xbmp.cpp \
    projects/PDBRipper/Formats/images/xgif.cpp \
    projects/PDBRipper/Formats/images/xicon.cpp \
    projects/PDBRipper/Formats/images/xjpeg.cpp \
    projects/PDBRipper/Formats/images/xpng.cpp \
    projects/PDBRipper/Formats/images/xtiff.cpp \
    projects/PDBRipper/Formats/subdevice.cpp \
    projects/PDBRipper/Formats/video/xmp4.cpp \
    projects/PDBRipper/Formats/video/xriff.cpp \
    projects/PDBRipper/Formats/xbinary.cpp \
    projects/PDBRipper/Formats/xdataconvertor.cpp \
    projects/PDBRipper/Formats/xformats.cpp \
    projects/PDBRipper/Formats/xiodevice.cpp \
    projects/PDBRipper/XAboutWidget/xaboutwidget.cpp \
    projects/PDBRipper/XGithub/xgithub.cpp \
    projects/PDBRipper/XOptions/codecs/codec_cp437.cpp \
    projects/PDBRipper/XOptions/dialogviewcolors.cpp \
    projects/PDBRipper/XOptions/xoptions.cpp \
    projects/PDBRipper/XOptions/xoptionswidget.cpp \
    projects/PDBRipper/XShortcuts/dialogshortcuts.cpp \
    projects/PDBRipper/XShortcuts/xshortcuts.cpp \
    projects/PDBRipper/XShortcuts/xshortcutsdialog.cpp \
    projects/PDBRipper/XShortcuts/xshortcutstscrollarea.cpp \
    projects/PDBRipper/XShortcuts/xshortcutswidget.cpp \
    projects/PDBRipper/XUpdate/xupdate.cpp \
    projects/PDBRipper/XWinPDB/msdia/diaCreate.cpp \
    projects/PDBRipper/XWinPDB/xwinpdb.cpp \
    projects/PDBRipper/console_source/consoleoutput.cpp \
    projects/PDBRipper/console_source/main_console.cpp \
    projects/PDBRipper/gui_source/dialogabout.cpp \
    projects/PDBRipper/gui_source/dialogexport.cpp \
    projects/PDBRipper/gui_source/dialogoptions.cpp \
    projects/PDBRipper/gui_source/dialogprocess.cpp \
    projects/PDBRipper/gui_source/guimainwindow.cpp \
    projects/PDBRipper/gui_source/main_gui.cpp \
    projects/PDBRipper/msdia/diaCreate.cpp \
    projects/PDBRipper/pdbprocess.cpp \
    projects/PDBRipper/qwinpdb.cpp \
    projects/XOpcodeCalc/Controls/dialogbits8.cpp \
    projects/XOpcodeCalc/Controls/subclassofqstyleditemdelegate.cpp \
    projects/XOpcodeCalc/Controls/xabstracttableview.cpp \
    projects/XOpcodeCalc/Controls/xcomboboxex.cpp \
    projects/XOpcodeCalc/Controls/xdatetimeeditx.cpp \
    projects/XOpcodeCalc/Controls/xdevicetableeditview.cpp \
    projects/XOpcodeCalc/Controls/xdevicetableview.cpp \
    projects/XOpcodeCalc/Controls/xheaderview.cpp \
    projects/XOpcodeCalc/Controls/xhtml.cpp \
    projects/XOpcodeCalc/Controls/xlineedithex.cpp \
    projects/XOpcodeCalc/Controls/xlineeditvalidator.cpp \
    projects/XOpcodeCalc/Controls/xsortfilterproxymodel.cpp \
    projects/XOpcodeCalc/Controls/xtableview.cpp \
    projects/XOpcodeCalc/XAboutWidget/xaboutwidget.cpp \
    projects/XOpcodeCalc/XGithub/xgithub.cpp \
    projects/XOpcodeCalc/XOptions/codecs/codec_cp437.cpp \
    projects/XOpcodeCalc/XOptions/dialogviewcolors.cpp \
    projects/XOpcodeCalc/XOptions/xoptions.cpp \
    projects/XOpcodeCalc/XOptions/xoptionswidget.cpp \
    projects/XOpcodeCalc/XShortcuts/dialogshortcuts.cpp \
    projects/XOpcodeCalc/XShortcuts/xshortcuts.cpp \
    projects/XOpcodeCalc/XShortcuts/xshortcutsdialog.cpp \
    projects/XOpcodeCalc/XShortcuts/xshortcutstscrollarea.cpp \
    projects/XOpcodeCalc/XShortcuts/xshortcutswidget.cpp \
    projects/XOpcodeCalc/XUpdate/xupdate.cpp \
    projects/XOpcodeCalc/gui_source/dialogabout.cpp \
    projects/XOpcodeCalc/gui_source/dialogoptions.cpp \
    projects/XOpcodeCalc/gui_source/guimainwindow.cpp \
    projects/XOpcodeCalc/gui_source/main_gui.cpp \
    projects/XOpcodeCalc/gui_source/modevalidator.cpp
